import approximation.test as test

names = ['Jacobi', 'Gauss-Seidel', 'Gauss-Seidel own sparse', 'Gauss-Seidel scipy.sparse', 'Partial Gauss']
values3 = [0.001, 0.0001, 0.00001]
values4 = [1, 2, 3]
values = [0.00001]
values2 = [1000]
a1 = test.Test('64_plasko.csv', 'result.txt', values, values2, names[0])
b1 = test.Test('64_plasko.csv', 'result.txt', values, values2, names[1])
c1 = test.Test('64_plasko.csv', 'result.txt', values, values2, names[2])
d1 = test.Test('64_plasko.csv', 'result.txt', values, values2, names[4])
e1 = test.Test('64_plasko.csv', 'result.txt', values, values2, names[3])
a1.jacobi()
b1.gs()
c1.gso()
d1.pg()
e1.gsparse()
a2 = test.Test('64_gorzysto.csv', 'result.txt', values, values2, names[0])
b2 = test.Test('64_gorzysto.csv', 'result.txt', values, values2, names[1])
c2 = test.Test('64_gorzysto.csv', 'result.txt', values, values2, names[2])
d2 = test.Test('64_gorzysto.csv', 'result.txt', values, values2, names[4])
e2 = test.Test('64_gorzysto.csv', 'result.txt', values, values2, names[3])
a2.jacobi()
b2.gs()
c2.gso()
d2.pg()
e2.gsparse()
a3 = test.Test('64_srednio.csv', 'result.txt', values, values2, names[0])
b3 = test.Test('64_srednio.csv', 'result.txt', values, values2, names[1])
c3 = test.Test('64_srednio.csv', 'result.txt', values, values2, names[2])
d3 = test.Test('64_srednio.csv', 'result.txt', values, values2, names[4])
e3 = test.Test('64_srednio.csv', 'result.txt', values, values2, names[3])
a3.jacobi()
b3.gs()
c3.gso()
d3.pg()
e3.gsparse()
a4 = test.Test('256_plasko.csv', 'result.txt', values, values2, names[0])
b4 = test.Test('256_plasko.csv', 'result.txt', values, values2, names[1])
c4 = test.Test('256_plasko.csv', 'result.txt', values, values2, names[2])
d4 = test.Test('256_plasko.csv', 'result.txt', values, values2, names[4])
e4 = test.Test('256_plasko.csv', 'result.txt', values, values2, names[3])
a4.jacobi()
b4.gs()
c4.gso()
d4.pg()
e4.gsparse()
a5 = test.Test('256_srednio.csv', 'result.txt', values, values2, names[0])
b5 = test.Test('256_srednio.csv', 'result.txt', values, values2, names[1])
c5 = test.Test('256_srednio.csv', 'result.txt', values, values2, names[2])
d5 = test.Test('256_srednio.csv', 'result.txt', values, values2, names[4])
e5 = test.Test('256_srednio.csv', 'result.txt', values, values2, names[3])
a5.jacobi()
b5.gs()
c5.gso()
d5.pg()
e5.gsparse()
a6 = test.Test('256_gorzysto.csv', 'result.txt', values, values2, names[0])
b6 = test.Test('256_gorzysto.csv', 'result.txt', values, values2, names[1])
c6 = test.Test('256_gorzysto.csv', 'result.txt', values, values2, names[2])
d6 = test.Test('256_gorzysto.csv', 'result.txt', values, values2, names[4])
e6 = test.Test('256_gorzysto.csv', 'result.txt', values, values2, names[3])
a6.jacobi()
b6.gs()
c6.gso()
d6.pg()
e6.gsparse()
a7 = test.Test('512_gorzysto.csv', 'result.txt', values, values2, names[0])
b7 = test.Test('512_gorzysto.csv', 'result.txt', values, values2, names[1])
c7 = test.Test('512_gorzysto.csv', 'result.txt', values, values2, names[2])
d7 = test.Test('512_gorzysto.csv', 'result.txt', values, values2, names[4])
e7 = test.Test('512_gorzysto.csv', 'result.txt', values, values2, names[3])
a7.jacobi()
b7.gs()
c7.gso()
d7.pg()
e7.gsparse()
a8 = test.Test('512_plasko.csv', 'result.txt', values, values2, names[0])
b8 = test.Test('512_plasko.csv', 'result.txt', values, values2, names[1])
c8 = test.Test('512_plasko.csv', 'result.txt', values, values2, names[2])
d8 = test.Test('512_plasko.csv', 'result.txt', values, values2, names[4])
e8 = test.Test('512_plasko.csv', 'result.txt', values, values2, names[3])
a8.jacobi()
b8.gs()
c8.gso()
d8.pg()
e8.gsparse()
a9 = test.Test('512_srednio.csv', 'result.txt', values, values2, names[0])
b9 = test.Test('512_srednio.csv', 'result.txt', values, values2, names[1])
c9 = test.Test('512_srednio.csv', 'result.txt', values, values2, names[2])
d9 = test.Test('512_srednio.csv', 'result.txt', values, values2, names[4])
e9 = test.Test('512_srednio.csv', 'result.txt', values, values2, names[3])
a9.jacobi()
b9.gs()
c9.gso()
d9.pg()
e9.gsparse()
# bez partial gauss bo on nie obsługuje w ogóle iteracji/tolerancji
a10 = test.Test('512_plasko.csv', 'result.txt', values, values4, names[0])
b10 = test.Test('512_plasko.csv', 'result.txt', values, values4, names[1])
c10 = test.Test('512_plasko.csv', 'result.txt', values, values4, names[2])
e10 = test.Test('512_plasko.csv', 'result.txt', values, values4, names[3])
a10.jacobi()
b10.gs()
c10.gso()
e10.gsparse()
a11 = test.Test('512_plasko.csv', 'result.txt', values3, values2, names[0])
b11 = test.Test('512_plasko.csv', 'result.txt', values3, values2, names[1])
c11 = test.Test('512_plasko.csv', 'result.txt', values3, values2, names[2])
e11 = test.Test('512_plasko.csv', 'result.txt', values3, values2, names[3])
a11.jacobi()
b11.gs()
c11.gso()
e11.gsparse()
